version: '3.7'

services:
  db:
      image: postgres
      container_name: db
      restart: always
      shm_size: 128mb
      ports:
          - "5432:5432"
      environment:
          POSTGRES_DB: laravel
          POSTGRES_PASSWORD: example
      networks:
            - app-network

  adminer:
      image: adminer
      restart: always
      ports:
          - "8080:8080"
      networks:
            - app-network

  app:
      build:
          context: .
          dockerfile: Dockerfile
      container_name: app
      ports:
          - "8000:8000"
      volumes:
          - .:/var/www/html
      networks:
          - app-network

networks:
    app-network:
        driver: bridge
